### ISSUE TITLE
FXAA not working on Radeon R9 m370x

### ISSUE THREAD

**Issue by menik66** [v002/v002-FXAA#1]
FXAA plugin does not work with Radeon R9 m370x on the new retina macbook pro
[Quartz Composer_2016-02-02-114919_globallocal.hang.zip](https://github.com/v002/v002-FXAA/files/114160/Quartz.Composer_2016-02-02-114919_globallocal.hang.zip)

**Comment by vade** [comment]
i need a crash log, and a patch. thanks.

**Comment by menik66** [comment]
Will try and add a crash log later.

Here is the .qtz file i was using.

[fxaa multipass.qtz.zip](https://github.com/v002/v002-FXAA/files/114180/fxaa.multipass.qtz.zip)

[v002 FXAA.plugin.zip](https://github.com/v002/v002-FXAA/files/114183/v002.FXAA.plugin.zip)

**Comment by vade** [comment]
Thanks. Another user sent over some info that is helpful. Ill look into it!

**Comment by vade** [comment]
Please try the new 1.1 release at : https://github.com/v002/v002-FXAA/releases 

And let me know if this works. Appreciate it!

**Comment by vade** [comment]
confirmed fixed in 1.1
